{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harperdb.secretName" . }}
  labels:
    {{- include "harperdb.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.entries | nindent 2 }}
{{- end }}
